g++ -o nal_type_test nal_type_test.c nal_type.c -I../../include/  -I../../../pjlib/include

../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -o session_info_test session_info_test.c session_info.c packet.c nal_type.c jitter_utility.c ../pjmedia/key_frame.c -I../../include/ -I../../../pjlib/include/  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog

g++ -I${GTEST_DIR}/include -I../../../pjlib/include -I../../include inter_frame_delay.c inter_frame_delay_test.c ${GTEST_DIR}/libgtest.a -o inter_frame_delay_test -lpthread

g++ -I${GTEST_DIR}/include -I../../../pjlib/include -I../../include jitter_estimator.c jitter_estimator_test.c ${GTEST_DIR}/libgtest.a -o jitter_estimator_test -lpthread

../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -I${GTEST_DIR}/include -I../../../pjlib/include -I../../include frame_buffer.c session_info.c packet.c jitter_utility.c decode_state.c decode_state_test.c nal_type.c ../pjmedia/key_frame.c ${GTEST_DIR}/libgtest.a -o decode_state_test -lpthread  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog 


#../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -I../../../../../../platforms/android-14/arch-arm/usr/include/ -I${GTEST_DIR}/include -I../../../pjlib/include -I../../include frame_buffer.c session_info.c packet.c jitter_utility.c decode_state.c decode_state_test.c nal_type.c ../pjmedia/key_frame.c ${GTEST_DIR}/lib/.libs/libgtest.a -o decode_state_test -lpthread  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a  ../../../../../..//out/apps/pjsip/armeabi-v7a/libstlport_static.a ../../../../../../out/apps/pjsip/armeabi-v7a/libilbc.a ../../../../../../out/apps/pjsip/armeabi-v7a/libstdc++.a  -L../../../../../..//platforms/android-14/arch-arm/usr/lib -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog -I../../../../../../sources/cxx-stl/stlport/stlport -I../../../../../../sources/cxx-stl/system/include  -DANDROID

../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -o decode_state_test decode_state_test.c decode_state.c frame_buffer.c session_info.c packet.c nal_type.c jitter_utility.c ../pjmedia/key_frame.c -I../../include/ -I../../../pjlib/include/  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog

../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -o timestamp_extrapolator_test timestamp_extrapolator_test.c timestamp_extrapolator.c  -I../../include/ -I../../../pjlib/include/  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog

../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -o decode_timer_test decode_timer.c decode_timer_test.c -I../../include/ -I../../../pjlib/include/  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog

../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -o timing_test timing.c timing_test.c timestamp_extrapolator.c decode_timer.c jitter_utility.c -I../../include/ -I../../../pjlib/include/  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog

../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -o jitter_buffer_test jitter_buffer_test.c jitter_buffer.c frame_buffer.c session_info.c packet.c nal_type.c jitter_estimator.c inter_frame_delay.c decode_state.c ../pjmedia/key_frame.c timestamp_extrapolator.c decode_timer.c jitter_utility.c ../utility/event_posix.c -I../../include/ -I../../../pjlib/include/  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog
../../../../../../toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -o jitter_buffer_nack_list_test jitter_buffer_nack_list_test.c jitter_buffer.c frame_buffer.c session_info.c  packet.c nal_type.c jitter_estimator.c inter_frame_delay.c decode_state.c ../pjmedia/key_frame.c timestamp_extrapolator.c decode_timer.c jitter_utility.c ../utility/event_posix.c -I../../include/ -I../../../pjlib/include/  ../../../../../../out/apps/pjsip/armeabi-v7a/libpjlib.a -lstdc++ -lc -lm -lsupc++ --sysroot=../../../../../../platforms/android-14/arch-arm -llog
